export const LANDING = {
  es: {
    nav: { enter: "Entrar" },
    hero: {
      badge: "Prospección B2B Inteligente",
      title: "Deja de golpear puertas a ciegas. Encuentra clientes calificados en tu ciudad",
      titleHighlight: "en 3 clics.",
      subtitle: "El software de prospección B2B que mapea tu región, extrae contactos reales y llena tu WhatsApp de empresas listas para comprar.",
      cta: "Crear mi cuenta GRATIS",
      noteBefore: "No requiere tarjeta. Al entrar, selecciona la pestaña ",
      noteStrong: "Sign up",
      noteAfter: " para crear tu cuenta.",
      mockFilters: ["País", "Estado", "Ciudad", "Nicho"],
      mockSearch: "Buscar Leads",
      mockLocation: "Bogotá, Colombia",
      mockBadge: "+42 leads encontrados ✓",
    },
    pains: {
      titleBefore: "¿Por qué tu equipo comercial está ",
      titleHighlight: "perdiendo dinero",
      titleAfter: " hoy?",
      items: [
        { title: "Listas frías y desactualizadas", desc: "Compras bases de datos donde el 70% de los números ya no existen." },
        { title: "Tiempo perdido", desc: "Horas buscando en internet en lugar de estar negociando y cerrando ventas." },
        { title: "Rutas ineficientes", desc: "Vendedores cruzando la ciudad para visitar negocios que no tienen el perfil de compra." },
      ],
    },
    solution: {
      titleBefore: "Tu nuevo ",
      titleHighlight: "radar de ventas B2B.",
      titleAfter: " Diseñado para cerrar negocios.",
      subtitle: "Todo lo que necesitas para prospectar, contactar y gestionar tus leads.",
      features: [
        { icon: "🎯", title: "Precisión Geográfica", desc: "Filtra exactamente por País, Estado y Ciudad para encontrar leads en tu zona objetivo." },
        { icon: "⚡", title: "Contacto Directo", desc: "Extraemos el teléfono público del negocio para que inicies la conversación por WhatsApp al instante." },
        { icon: "📊", title: "CRM Visual Integrado", desc: "Guarda tus leads y muévelos por un embudo de ventas intuitivo sin salir de la plataforma." },
        { icon: "⭐", title: "Radar de Oportunidades", desc: "Filtra negocios por su reputación en Google para encontrar clientes que necesitan tus servicios de marketing hoy mismo." },
        { icon: "🌐", title: "Inteligencia Social", desc: "Ahorra horas de investigación: Accede al Sitio Web y al Instagram de tu prospecto con un solo clic desde tu CRM." },
      ],
    },
    useCase: {
      badge: "Caso de uso real",
      title: "De la búsqueda a la ruta logística en minutos.",
      p1: "Imagina que eres un distribuidor. Abres nuestra plataforma, filtras ",
      strong1: '"Bogotá"',
      p2: " y buscas ",
      strong2: '"Panaderías Artesanales"',
      p3: ". En 10 segundos, tienes una lista con la dirección exacta y el WhatsApp del dueño.",
      costNote: "Tu costo de adquisición de clientes acaba de caer un 80%.",
      imageAlt: "Distribuidor de productos verificando el mapa de rutas logísticas",
      imageBadge: "47 panaderías encontradas",
    },
    testimonials: {
      title: "Únete a cientos de equipos que ya no pierden tiempo",
      subtitle: "Lo que dicen los profesionales que prospectan con LeadZone.",
      items: [
        { name: "Carlos Mendoza", role: "Director Comercial, TechB2B", content: "Antes pasábamos horas buscando en Google Maps. Ahora, filtramos nuestra ciudad y en 2 minutos tenemos una lista lista para enviar WhatsApps. Nuestro equipo cierra el doble de reuniones.", rating: 5 },
        { name: "Laura Gómez", role: "Agente Independiente", content: "El mejor SaaS de prospección que he probado. El hecho de que extraiga el número de teléfono directo me ha ahorrado días de trabajo. Se paga solo con la primera venta.", rating: 5 },
        { name: "Diego Sánchez", role: "CEO, Distribuidora Sur", content: "Mapear restaurantes y cafeterías para nuestra distribución solía ser un dolor de cabeza. Con LeadZone, creamos rutas precisas en minutos. Brutal.", rating: 5 },
      ],
    },
    pricing: {
      titleBefore: "Una inversión que se paga con ",
      titleHighlight: "tu primera venta del mes.",
      subtitle: "Empieza gratis, descubre el poder de la prospección inteligente y escala según el tamaño de tu negocio.",
      plans: [
        { id: "free", name: "Gratuito", price: "$0", period: "/mes", tag: null, description: "Para probar el motor de búsqueda.", features: ["3 búsquedas/día", "Búsqueda Latam", "5 resultados por búsqueda", "Embudo CRM básico"], cta: "Empezar Gratis", highlight: false, link: null },
        { id: "starter", name: "Starter", price: "$12", period: "/mes", tag: null, description: "Para el vendedor independiente.", features: ["120 búsquedas/mes", "Búsqueda Latam", "Paginación completa", "Soporte por email"], cta: "Elegir Starter", highlight: false, link: "https://pay.hotmart.com/N105430971V?off=ga1w2f7m" },
        { id: "pro", name: "Pro", price: "$25", period: "/mes", tag: "MÁS POPULAR", description: "Ideal para pequeñas empresas.", features: ["300 búsquedas/mes", "Búsqueda Global (Mundial)", "CRM completo", "Soporte prioritario"], cta: "Elegir Pro", highlight: true, link: "https://pay.hotmart.com/N105430971V?off=7plqhfor" },
        { id: "pro_max", name: "Pro Max", price: "$49", period: "/mes", tag: null, description: "Para equipos comerciales.", features: ["800 búsquedas/mes", "Todo lo del Pro", "Exportar CSV", "Filtro de Calificación Estratégica (Encuentra negocios con malas notas)", "Enlaces directos a Web e Instagram"], cta: "Elegir Pro Max", highlight: false, link: "https://pay.hotmart.com/N105430971V?off=4ziuiskw" },
        { id: "enterprise", name: "Enterprise", price: "$99", period: "/mes", tag: null, description: "Para distribuidores y agencias.", features: ["1500+ búsquedas/mes", "Todo lo del Pro Max", "API access", "Soporte dedicado", "Filtro de Calificación Estratégica (Encuentra negocios con malas notas)", "Enlaces directos a Web e Instagram"], cta: "Elegir Enterprise", highlight: false, link: "https://pay.hotmart.com/N105430971V?off=5ou2ljz4" },
      ],
    },
    faq: {
      title: "Preguntas Frecuentes",
      subtitle: "Todo lo que necesitas saber antes de empezar.",
      items: [
        { q: "¿De dónde provienen los datos?", a: "Extraemos información pública y actualizada en tiempo real directamente de motores de búsqueda y mapas (como Google), garantizando que los negocios sigan operando y los números estén activos." },
        { q: "¿Funciona en mi país o ciudad?", a: "Sí, LeadZone funciona en cualquier país de Latinoamérica y España. Solo tienes que buscar el país, estado y la ciudad exacta que deseas prospectar." },
        { q: "¿Necesito tarjeta de crédito para el plan gratis?", a: "No. Puedes crear tu cuenta y usar tus búsquedas diarias gratuitas sin introducir ningún método de pago. Empieza a prospectar al instante." },
        { q: "¿Puedo cancelar o cambiar mi plan en cualquier momento?", a: "Absolutamente. No hay contratos a largo plazo. Puedes subir de plan cuando tu equipo crezca o cancelar tu suscripción con un solo clic desde tu panel." },
      ],
    },
    finalCta: {
      title: "¿Listo para llenar tu pipeline?",
      subtitle: "Empieza gratis hoy. Sin tarjeta de crédito.",
      cta: "Crear mi cuenta GRATIS",
    },
    footer: {
      blog: "Blog",
      pricing: "Precios",
      rights: "© 2026 LeadZone. Todos los derechos reservados.",
    },
  },
  pt: {
    nav: { enter: "Entrar" },
    hero: {
      badge: "Prospecção B2B Inteligente",
      title: "Pare de bater em portas às cegas. Encontre clientes qualificados na sua cidade",
      titleHighlight: "em 3 cliques.",
      subtitle: "O software de prospecção B2B que mapeia sua região, extrai contatos reais e enche seu WhatsApp de empresas prontas para comprar.",
      cta: "Criar minha conta GRÁTIS",
      noteBefore: "Não precisa de cartão. Ao entrar, selecione a aba ",
      noteStrong: "Sign up",
      noteAfter: " para criar sua conta.",
      mockFilters: ["País", "Estado", "Cidade", "Nicho"],
      mockSearch: "Buscar Leads",
      mockLocation: "São Paulo, Brasil",
      mockBadge: "+42 leads encontrados ✓",
    },
    pains: {
      titleBefore: "Por que sua equipe comercial está ",
      titleHighlight: "perdendo dinheiro",
      titleAfter: " hoje?",
      items: [
        { title: "Listas frias e desatualizadas", desc: "Você compra bases de dados onde 70% dos números já não existem." },
        { title: "Tempo perdido", desc: "Horas pesquisando na internet em vez de estar negociando e fechando vendas." },
        { title: "Rotas ineficientes", desc: "Vendedores cruzando a cidade para visitar negócios que não têm perfil de compra." },
      ],
    },
    solution: {
      titleBefore: "Seu novo ",
      titleHighlight: "radar de vendas B2B.",
      titleAfter: " Feito para fechar negócios.",
      subtitle: "Tudo o que você precisa para prospectar, contatar e gerenciar seus leads.",
      features: [
        { icon: "🎯", title: "Precisão Geográfica", desc: "Filtre exatamente por País, Estado e Cidade para encontrar leads na sua região alvo." },
        { icon: "⚡", title: "Contato Direto", desc: "Extraímos o telefone público do negócio para você iniciar a conversa pelo WhatsApp na hora." },
        { icon: "📊", title: "CRM Visual Integrado", desc: "Salve seus leads e mova-os por um funil de vendas intuitivo sem sair da plataforma." },
        { icon: "⭐", title: "Radar de Oportunidades", desc: "Filtre negócios pela reputação no Google para encontrar clientes que precisam dos seus serviços de marketing hoje mesmo." },
        { icon: "🌐", title: "Inteligência Social", desc: "Economize horas de pesquisa: acesse o Site e o Instagram do seu prospect com um clique direto do seu CRM." },
      ],
    },
    useCase: {
      badge: "Caso de uso real",
      title: "Da busca à rota logística em minutos.",
      p1: "Imagine que você é um distribuidor. Abre nossa plataforma, filtra ",
      strong1: '"São Paulo"',
      p2: " e busca ",
      strong2: '"Padarias Artesanais"',
      p3: ". Em 10 segundos, você tem uma lista com o endereço exato e o WhatsApp do dono.",
      costNote: "Seu custo de aquisição de clientes acabou de cair 80%.",
      imageAlt: "Distribuidor de produtos verificando o mapa de rotas logísticas",
      imageBadge: "47 padarias encontradas",
    },
    testimonials: {
      title: "Junte-se a centenas de equipes que não perdem mais tempo",
      subtitle: "O que dizem os profissionais que prospectam com a LeadZone.",
      items: [
        { name: "Carlos Mendes", role: "Diretor Comercial, TechB2B", content: "Antes passávamos horas pesquisando no Google Maps. Agora, filtramos nossa cidade e em 2 minutos temos uma lista pronta para enviar WhatsApps. Nossa equipe fecha o dobro de reuniões.", rating: 5 },
        { name: "Laura Gomes", role: "Agente Independente", content: "O melhor SaaS de prospecção que já testei. O fato de extrair o número de telefone direto me economizou dias de trabalho. Se paga com a primeira venda.", rating: 5 },
        { name: "Diego Santos", role: "CEO, Distribuidora Sul", content: "Mapear restaurantes e cafeterias para nossa distribuição era uma dor de cabeça. Com a LeadZone, criamos rotas precisas em minutos. Sensacional.", rating: 5 },
      ],
    },
    pricing: {
      titleBefore: "Um investimento que se paga com ",
      titleHighlight: "sua primeira venda do mês.",
      subtitle: "Comece grátis, descubra o poder da prospecção inteligente e escale conforme o tamanho do seu negócio.",
      plans: [
        { id: "free", name: "Gratuito", price: "$0", period: "/mês", tag: null, description: "Para testar o motor de busca.", features: ["3 buscas/dia", "Busca Latam", "5 resultados por busca", "Funil CRM básico"], cta: "Começar Grátis", highlight: false, link: null },
        { id: "starter", name: "Starter", price: "$12", period: "/mês", tag: null, description: "Para o vendedor independente.", features: ["120 buscas/mês", "Busca Latam", "Paginação completa", "Suporte por email"], cta: "Escolher Starter", highlight: false, link: "https://pay.hotmart.com/N105430971V?off=ga1w2f7m" },
        { id: "pro", name: "Pro", price: "$25", period: "/mês", tag: "MAIS POPULAR", description: "Ideal para pequenas empresas.", features: ["300 buscas/mês", "Busca Global (Mundial)", "CRM completo", "Suporte prioritário"], cta: "Escolher Pro", highlight: true, link: "https://pay.hotmart.com/N105430971V?off=7plqhfor" },
        { id: "pro_max", name: "Pro Max", price: "$49", period: "/mês", tag: null, description: "Para equipes comerciais.", features: ["800 buscas/mês", "Tudo do Pro", "Exportar CSV", "Filtro de Avaliação Estratégica (Encontre negócios com notas baixas)", "Links diretos para Site e Instagram"], cta: "Escolher Pro Max", highlight: false, link: "https://pay.hotmart.com/N105430971V?off=4ziuiskw" },
        { id: "enterprise", name: "Enterprise", price: "$99", period: "/mês", tag: null, description: "Para distribuidores e agências.", features: ["1500+ buscas/mês", "Tudo do Pro Max", "Acesso à API", "Suporte dedicado", "Filtro de Avaliação Estratégica (Encontre negócios com notas baixas)", "Links diretos para Site e Instagram"], cta: "Escolher Enterprise", highlight: false, link: "https://pay.hotmart.com/N105430971V?off=5ou2ljz4" },
      ],
    },
    faq: {
      title: "Perguntas Frequentes",
      subtitle: "Tudo o que você precisa saber antes de começar.",
      items: [
        { q: "De onde vêm os dados?", a: "Extraímos informações públicas e atualizadas em tempo real diretamente de motores de busca e mapas (como o Google), garantindo que os negócios continuem operando e os números estejam ativos." },
        { q: "Funciona no meu país ou cidade?", a: "Sim, a LeadZone funciona em qualquer país da América Latina, incluindo o Brasil. Basta buscar o país, estado e a cidade exata que deseja prospectar." },
        { q: "Preciso de cartão de crédito para o plano grátis?", a: "Não. Você pode criar sua conta e usar suas buscas diárias gratuitas sem inserir nenhum método de pagamento. Comece a prospectar na hora." },
        { q: "Posso cancelar ou trocar de plano a qualquer momento?", a: "Com certeza. Não há contratos de longo prazo. Você pode subir de plano quando sua equipe crescer ou cancelar sua assinatura com um clique no seu painel." },
      ],
    },
    finalCta: {
      title: "Pronto para encher seu pipeline?",
      subtitle: "Comece grátis hoje. Sem cartão de crédito.",
      cta: "Criar minha conta GRÁTIS",
    },
    footer: {
      blog: "Blog",
      pricing: "Preços",
      rights: "© 2026 LeadZone. Todos os direitos reservados.",
    },
  },
};